### ISSUE TITLE
alacritty

### ISSUE THREAD

**Issue by nymann** [nymann/dotfiles#4]
```yml
schemes:
  tokyo-night: &ref_0
    # Default colors
    # Default colors
    primary:
      background: "#1D202F"
      foreground: "#a9b1d6"

    # Normal colors
    normal:
      black: "#32344a"
      red: "#f7768e"
      green: "#9ece6a"
      yellow: "#e0af68"
      blue: "#7aa2f7"
      magenta: "#A24FA1"
      cyan: "#449dab"
      white: "#787c99"

    # Bright colors
    bright:
      black: "#444b6a"
      red: "#ff7a93"
      green: "#b9f27c"
      yellow: "#ff9e64"
      blue: "#7da6ff"
      magenta: "#bb9af7"
      cyan: "#0db9d7"
      white: "#acb0d0"

  tokyo-night-storm: &tokyo-night-storm # Default colors
    primary:
      background: "#24283b"
      foreground: "#a9b1d6"

    # Normal colors
    normal:
      black: "#32344a"
      red: "#f7768e"
      green: "#9ece6a"
      yellow: "#e0af68"
      blue: "#7aa2f7"
      magenta: "#ad8ee6"
      cyan: "#449dab"
      white: "#9699a8"

    # Bright colors
    bright:
      black: "#444b6a"
      red: "#ff7a93"
      green: "#b9f27c"
      yellow: "#ff9e64"
      blue: "#7da6ff"
      magenta: "#bb9af7"
      cyan: "#0db9d7"
      white: "#acb0d0"
  papercolorlight:
    primary:
      background: "#eeeeee"
      foreground: "#878787"
    cursor:
      text: "#eeeeee"
      cursor: "#878787"
    normal:
      black: "#eeeeee"
      red: "#af0000"
      green: "#008700"
      yellow: "#5f8700"
      blue: "#0087af"
      magenta: "#878787"
      cyan: "#005f87"
      white: "#444444"
    bright:
      black: "#bcbcbc"
      red: "#d70000"
      green: "#d70087"
      yellow: "#8700af"
      blue: "#d75f00"
      magenta: "#d75f00"
      cyan: "#005faf"
      white: "#005f87"
  nord:
    primary:
      background: "#2e3440"
      foreground: "#e5e9f0"
    cursor:
      text: "#2e3440"
      cursor: "#e5e9f0"
    normal:
      black: "#2e3440"
      red: "#88c0d0"
      green: "#a3be8c"
      yellow: "#5e81ac"
      blue: "#ebcb8b"
      magenta: "#bf616a"
      cyan: "#d08770"
      white: "#e5e9f0"
    bright:
      black: "#4c566a"
      red: "#88c0d0"
      green: "#bf616a"
      yellow: "#5e81ac"
      blue: "#ebcb8b"
      magenta: "#a3be8c"
      cyan: "#d08770"
      white: "#8fbcbb"
    indexed_colors:
      - index: 16
        color: "#81a1c1"
      - index: 17
        color: "#b48ead"
      - index: 18
        color: "#3b4252"
      - index: 19
        color: "#434c5e"
      - index: 20
        color: "#d8dee9"
      - index: 21
        color: "#eceff4"
  onedark:
    primary:
      background: "#1e2127"
      foreground: "#abb2bf"
      bright_foreground: "#e6efff"
    normal:
      black: "#1e2127"
      red: "#e06c75"
      green: "#98c379"
      yellow: "#d19a66"
      blue: "#61afef"
      magenta: "#c678dd"
      cyan: "#56b6c2"
      white: "#828791"
    bright:
      black: "#5c6370"
      red: "#e06c75"
      green: "#98c379"
      yellow: "#d19a66"
      blue: "#61afef"
      magenta: "#c678dd"
      cyan: "#56b6c2"
      white: "#e6efff"
    dim:
      black: "#1e2127"
      red: "#e06c75"
      green: "#98c379"
      yellow: "#d19a66"
      blue: "#61afef"
      magenta: "#c678dd"
      cyan: "#56b6c2"
      white: "#828791"
  tokynight:
    primary:
      background: "#1a1b26"
      foreground: "#c0caf5"

    # Normal colors
    normal:
      black: "#15161E"
      red: "#f7768e"
      green: "#9ece6a"
      yellow: "#e0af68"
      blue: "#7aa2f7"
      magenta: "#bb9af7"
      cyan: "#7dcfff"
      white: "#a9b1d6"

    # Bright colors
    bright:
      black: "#414868"
      red: "#f7768e"
      green: "#9ece6a"
      yellow: "#e0af68"
      blue: "#7aa2f7"
      magenta: "#bb9af7"
      cyan: "#7dcfff"
      white: "#c0caf5"

    indexed_colors:
      - { index: 16, color: "#ff9e64" }
      - { index: 17, color: "#db4b4b" }
colors: *ref_0
window:
  opacity: 1
  padding:
    x: 5
    y: 5
font:
  normal:
    family: RobotoMono Nerd Font
    style: Regular
  bold:
    family: RobotoMono Nerd Font
    style: Bold
  italic:
    family: RobotoMono Nerd Font
    style: Italic
key_bindings:
  - key: Return
    mods: Control|Shift
    action: SpawnNewInstance
enable_rgb: true

```
